### ISSUE TITLE
[Update]

### ISSUE THREAD

**Issue by librarian-pku** [lib-pku/libpku#1]
大家好，

不知道这个仓库为什么突然受到很大关注。。
我注意到各种声音，在这里稍微反馈一下我的想法：
见 https://github.com/lib-pku/libpku#license ，资料整理自网络，由于种种原因可能原作者不可考、没有标记清楚，是我的疏忽。我只进行了收集，没有再分发。
**我们不会为收集到的资料收费，或是尝试收取捐赠** 。这句话其实是在讽刺什么，懂的人自然懂，不多说。
**我们只是尝试为后来的同学节省一些时间。** 这是我和几个朋友整理这些资料的出发点，希望可以把我们浪费掉的一些时间省下来，希望学弟学妹们可以把时间花在更重要的事情上。

顺便有一个问题想抛出来和大家探讨：为什么一个收费的资料库无人举报，但是免费的资料库就有很多人踊跃举报呢？如果说把网上已经有的课程资料整理一下是件错事，那为什么对这些资料收费就是对的呢？

祝好

**Comment by eyea** [comment]
专注现在合理的分享精神，支持你！
