### ISSUE TITLE
项目是否征询了相关任课老师的同意

### ISSUE THREAD

**Issue by SN-1604** [lib-pku/libpku#12]
课程资料和试卷是课程任课老师的心血，老师本人理应享有相关知识产权，据本人了解，很多老师是很反感自己整理的资料讲义和试卷被盗用的，考试结束后试卷也会回收处理，该项目如果未征得相关任课老师同意就将这些资料进行开源，本身也侵犯了老师们的权益，即便从礼貌和道德角度考虑，使用他人东西前征询本人意见也是前提，希望项目的贡献者提供说明。

**Comment by shixianghui** [comment]
复议！

**Comment by forrestchang** [comment]
根据 Fork 的数量来看，即使要求删除也没有用了。

**Comment by Huangzhongyi028** [comment]
附议版权问题

**Comment by fibercoke** [comment]
这个项目就不应该出现

**Comment by fibercoke** [comment]
建议架个校内ftp。

**Comment by JohnGuan** [comment]
这等内容，可能看到都得先fo为敬了

**Comment by anzipomelo** [comment]
> 课程资料和试卷是课程任课老师的心血，老师本人理应享有相关知识产权，据本人了解，很多老师是很反感自己整理的资料讲义和试卷被盗用的，考试结束后试卷也会回收处理，该项目如果未征得相关任课老师同意就将这些资料进行开源，本身也侵犯了老师们的权益，即便从礼貌和道德角度考虑，使用他人东西前征询本人意见也是前提，希望项目的贡献者提供说明。

我在百度文库看到很多讲义了，感觉有些老师是万年讲义没变过

**Comment by Giccuk** [comment]
附议

**Comment by acaly** [comment]
个人觉得如果不是北京大学官方，使用这样一个用户名和项目名是非常非常有误导性的，即使是在说明中提到了这一点也一样。

**Comment by liruiyuan2018** [comment]
小家子气

**Comment by lijinbia** [comment]
有教无类 很好

**Comment by Harold-Fu** [comment]
@liruiyuan2018
说版权是小家子气的感觉只能是非蠢即坏了，作为学者，老师们一生最宝贵的财富就是自己所生产的课程资料/学术成果，我不反对把课程资料开放给校外有需要的人士，但是是否应该先征求老师意见？要不我们不经过你同意从你的银行把你的工资拿出来给大家分享一下？

**Comment by liruiyuan2018** [comment]
> @liruiyuan2018
> 说版权是小家子气的感觉只能是非蠢即坏了，作为学者，老师们一生最宝贵的财富就是自己所生产的课程资料/学术成果，我不反对把课程资料开放给校外有需要的人士，但是是否应该先征求老师意见？要不我们不经过你同意从你的银行把你的工资拿出来给大家分享一下？

是你自己蠢吧？那些考卷什么是版权？你查查什么是版权再来说话。
考卷什么的也是学术成果了？有法律支持吗？
一边说不反对把他拿出来，一边又把它和工资相比较，你的逻辑到底在那里？

**Comment by Harold-Fu** [comment]
公民为完成法人或者其他组织工作任务所创作的作品是职务作品，除本条第二款的规定以外，著作权由作者享有，但法人或者其他组织有权在其业务范围内优先使用。 作品完成两年内，未经单位同意，作者不得许可第三人以与单位使用的相同方式使 用该作品。有下列情形之一的职务作品，作者享有署名权，著作权的其他权利由法 人或者其他组织享有，法人或者其他组织可以给予作者奖励:(一)主要是利用法 人或者其他组织的物质技术条件创作，并由法人或者其他组织承担责任的工程设计 图、产品设计图、地图、计算机软件等职务作品;(二)法律、行政法规规定或者 合同约定著作权由法人或者其他组织享有的职务作品。
——中华人民共和国著作权法第十六条
关于试卷是否是职务作品，你可以问任意一个律师，或者看一下这篇论文：
http://www.wanfangdata.com.cn/details/detail.do?_type=degree&id=D090397

我不反对把它们公开，前提是老师同意，是在他的权利得到尊重的情况下，我支持知识的开放，但是在著作权被侵犯的情况下，我反对公开。

没有逻辑的到底是谁呢？

**Comment by liruiyuan2018** [comment]
> 公民为完成法人或者其他组织工作任务所创作的作品是职务作品，除本条第二款的规定以外，著作权由作者享有，但法人或者其他组织有权在其业务范围内优先使用。 作品完成两年内，未经单位同意，作者不得许可第三人以与单位使用的相同方式使 用该作品。有下列情形之一的职务作品，作者享有署名权，著作权的其他权利由法 人或者其他组织享有，法人或者其他组织可以给予作者奖励:(一)主要是利用法 人或者其他组织的物质技术条件创作，并由法人或者其他组织承担责任的工程设计 图、产品设计图、地图、计算机软件等职务作品;(二)法律、行政法规规定或者 合同约定著作权由法人或者其他组织享有的职务作品。
> ——中华人民共和国著作权法第十六条
> 关于试卷是否是职务作品，你可以问任意一个律师，或者看一下这篇论文：
> http://www.wanfangdata.com.cn/details/detail.do?_type=degree&id=D090397
> 
> 我不反对把它们公开，前提是老师同意，是在他的权利得到尊重的情况下，我支持知识的开放，但是在著作权被侵犯的情况下，我反对公开。
> 
> 没有逻辑的到底是谁呢？

说实在的，我就看了你给的链接摘要，我都没看你给的论文，为什么呢？没用。
摘要说“从三个方面对试卷的版权问题进行了探讨。”
探讨，显然是该论题不清，才探讨，如果像你的似的任何一位律师都认为试卷是版权，有著作权，还探讨个啥?还写啥论文？
既然是论文，只要有兴趣，别人也完全可以写出个论文支持他没有著作权。

我说你逻辑不清是把试卷比作工资，工资显然是个人财产，受法律严格保护，这个不用写论文论证，没有任何疑问。

**Comment by Harold-Fu** [comment]
你非要对准试卷不放也行，教育部《高等学校知识产权保护管理规定》第九条：“”由高等学校主持、代表高等学校意志创作、并由高等学校承担责任的作品为高等学校法人作品，其著作权由高等学校享有。为完成高等学校的工作任务所创作的作品是职务作品，除第十条规定情况外，著作权由完成者享有。高等学校在其业务范围内对职务作品享有优先使用权。作品完成二年内，未经高等学校同意，作者不得许可第三人以与高等学校相同的方式使用该作品。”
你的工资受法律保护没有争议，试卷受法律保护就有争议了？是否有争议不是你一个人说了算的。

**Comment by liruiyuan2018** [comment]
> 你非要对准试卷不放也行，教育部《高等学校知识产权保护管理规定》第九条：“”由高等学校主持、代表高等学校意志创作、并由高等学校承担责任的作品为高等学校法人作品，其著作权由高等学校享有。为完成高等学校的工作任务所创作的作品是职务作品，除第十条规定情况外，著作权由完成者享有。高等学校在其业务范围内对职务作品享有优先使用权。作品完成二年内，未经高等学校同意，作者不得许可第三人以与高等学校相同的方式使用该作品。”
> 你的工资受法律保护没有争议，试卷受法律保护就有争议了？是否有争议不是你一个人说了算的。

如果没有争议，上面你给的那篇论文又在"探讨"呢？
如果问题这么简单，一个第9条就可以解决的问题，你上面引用的那篇论文又旁征博引的“探讨”啥呢？又在论啥呢？

**Comment by Krantz-XRF** [comment]
我看二位也不用在这里争得面红耳赤，无论老师是否拥有试卷的著作权，在公开发表之前征得老师的同意都是基本的礼貌。现在的问题不是真的有老师来追究这个repo的法律责任，而是我们在讨论“不经老师允许发表包括试卷在内的课程资料”属于对老师工作的不尊重。法律是自律的底线，而不是最高标准，我们作为北大学生更应该懂得敬重知识以及知识的传播者。

此外，有很多课程资料授课老师也不享有著作权，而是引用自一些学术会议等报告的slides，这种材料的传播需要原始作者的授权，本着共享的原则盲目扩散可能会导致授课老师间接侵权，这也是我们都不想看到的。

**Comment by librarian-pku** [comment]
@SN-1604 谢谢提醒，是我考虑不周了，并没有事先征询老师意见，希望日后有机会能联系老师，现在已经注册了邮箱，如果有人联系我希望删除内容的话也会删除。
@acaly 谢谢提醒，已经修改。
@Krantz-XRF 谢谢，说得很对。

**Comment by acaly** [comment]
我指的是url里的lib-pku/libpku，这个容易让人以为是北京大学官方发布的（虽然稍微动脑子想想就会发觉不太对）

**Comment by shanzhoupeng** [comment]
呵呵 这就是有些老师永远不换试题 然后无视有人能拿到原题有人拿不到的实际情况的理由吗？

从不换题懒得要死 不以为耻反以为荣

**Comment by firefoxhome** [comment]
我早就受够了，某些人靠拉关系从高年级手中得到万年不变的试题。平时不学习，考试得高分，呵呵。真是做的一手好交易。
  

 

 ------------------ 原始邮件 ------------------
  发件人: "zhefeng shen"<notifications@github.com>;
 发送时间: 2019年6月14日(星期五) 下午5:41
 收件人: "lib-pku/libpku"<libpku@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>;
 主题: Re: [lib-pku/libpku] 项目是否征询了相关任课老师的同意 (#12)

 

 
呵呵 这就是有些老师永远不换试题 然后无视有人能拿到原题有人拿不到的实际情况的理由吗？
 
从不换题懒得要死 不以为耻反以为荣
