### ISSUE TITLE
文件太大，建议用网盘形式存储

### ISSUE THREAD

**Issue by levypan666** [lib-pku/libpku#16]
课程文件太大了，建议用One Drive 或者 Google Drive的形式存储，在github上放链接

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by MiracleTaoTao** [comment]
> One Drive和Google Drive的免费空间比较小。

应该比GitHub的空间要大一点，我记得GitHub每个项目的空间是有限的，超过了官方会发邮件的

**Comment by librarian-pku** [comment]
谢谢！
