### ISSUE TITLE
开源、分享、贡献

### ISSUE THREAD

**Issue by chao921125** [lib-pku/libpku#18]
看到12楼楼主的的建议了，很好，这个建议博主参考下，若是有人附议并提出相关证据可以将其下架。不过，现在都是什么时代了？还闭关锁国，不求上进，不开源，老思想，闭门造车你能造出来个鬼？

**Comment by liruiyuan2018** [comment]
支持。
根本也没有证据说试卷是老师的学术成果或私有财产。
至于有些人提的都是考试完收试卷那大部分是因为考题千年不变。
什么事都有人想从什么道义上当个圣母，看似是个文明道士，其实就是个SX

**Comment by librarian-pku** [comment]
谢谢！
