### ISSUE TITLE
麻烦用中性的大学名称。

### ISSUE THREAD

**Issue by aiyolo** [lib-pku/libpku#24]
贵校一词的词汇色彩难以让我接受，也不利于项目传播。

_Sent from my MI 8 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by NOforgetQY** [comment]
可能是因为一些特殊原因吧，但是贵校一词的确有点让人难以捉摸

**Comment by foreverfrp** [comment]
> 贵校一词的词汇色彩难以让我接受，也不利于项目传播。
> 
> _Sent from my MI 8 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

改成“隔壁”…2333

**Comment by librarian-pku** [comment]
抱歉不是很懂有什么词汇色彩，改这个名是因为注意到可能会让人误以为是官方整理的仓库。
如有不当还请指正。
另外也不希望项目传播的说。
