### ISSUE TITLE
关于issues#12提到的版权问题

### ISSUE THREAD

**Issue by shanzhoupeng** [lib-pku/libpku#45]
从star和fork数可以看出，这个项目的影响力越来越大，假如不能坚持"开源，分享，贡献"的底线，假如随便一个没有被验证身份的人的要求都能删除资料的话，那这个项目到最后还会剩下什么呢？这个项目还有什么存在的意义呢

试卷重复使用本来就是教师对教学质量、试卷质量不够负责的行为，他们通过试卷保密的方式来减少自己的工作量的行为体现了他们懒惰的本质，全然不顾试卷本身已经在小范围内泄露的事实，只图自己方便的行为是绝对低劣的。每个人都可以随便google一下"algebraic topology"，看看能搜到多少知名大学的多少试卷？我们却反其道而行之，难道我们建设世界一流大学就是这样建设的吗?

我已经是毕业班的同学了，这个网站和我已经没那么大的利益联系了。实际上，我的愤怒来自政治试卷被删除的这个可笑事实，各个等级的政治试题在网上随处可见(初中，高中，考研，其他试卷)，这样一个没价值的东西，有人竟以"尊重版权"之名要求删除，您出的马原试卷可真有价值啊！对于这些任课老师，助教我只想说：LOW

最后是对项目发起者和维护者的话：#21中的2和4说的非常好，我敬佩你们的执行力，但请你们坚持本心，这个项目的本质我认为就是他的绝对分享性，不够绝对不够"硬"最终就会失去所有意义，就像我之前说的，随着影响力越来越大，会有越来越多的人要求删除资料，最后这个项目就会名存实亡。如果你们不想承担这在我看来莫须有的压力，可以找个自愿承担这个责任（法律）的人（比如我），转移责任。

**Comment by hydrahs** [comment]
何谓气度，这才是气度：）

**Comment by shanzhoupeng** [comment]
另外我想补充一点的是在我看来这个坚持这个项目和坚持绝对的共享原则的意义。我认为这个项目将是推动我校教学质量尤其是考试质量到下一个水平的重要助力。从我的经验来看，现在的很多课程考试变成了一种交差，老师随意出试卷，一用就是五六年。公开的试题资源可以迫使这些老师重新审视自己的教学大纲，重新构建完善合理的试题。这是他们在这样一所学校授课的责任和义务，也是他们应该付出精力做的。

我本人上过一门英语课，涉及到平时的小测。有一天这个老师发表了如下言论："这个课有两个班级，你们班先考，希望大家不要和下一个班级的同学交流试题","以北京大学学生的学术信誉balabala"。真是滑天下之大稽，学生遵守学生规范是学生的本分，但是本应维护考试纪律与公平的老师放弃自己的义务将责任全甩给"学术信誉"简直是既无耻又懒惰的行为。

**Comment by zahlkorper** [comment]
首先，感谢分享；
其次，未经授权而分享是违法的。就如分享盗版游戏一样，说得再高大上也都是错的。
最后，有时候老师也无可奈何，等再出个翟天临你们就老实了。
话不多说。

**Comment by librarian-pku** [comment]
感谢
政治课相关资料移除是因为之前放了一些某公众号整理的资料，由于没有精力进一步检查就全部移除了。
