### ISSUE TITLE
工作三年的搬砖码农，怀抱着对大学知识的景仰，默默关注

### ISSUE THREAD

**Issue by relign** [lib-pku/libpku#5]
工作三年，尤其在大厂，觉得自己的基础功不扎实，越来越觉得大学的基础知识无比重要，只后悔当初没有好好学习...

**Comment by librarian-pku** [comment]
谢谢！加油！

**Comment by yaeljiao** [comment]
兄弟，这个issue上了果壳的文章，小火了一把

**Comment by relign** [comment]
> 兄弟，这个issue上了果壳的文章，小火了一把

链接发一下
