### ISSUE TITLE
现在看了有 500 多兆，github 对这么大的文件处理会不会有缺陷

### ISSUE THREAD

**Issue by gaosjx** [lib-pku/libpku#8]

**Comment by librarian-pku** [comment]
有可能，但是一时没有想到有什么更适合的方式，欢迎提出更好的方案

**Comment by forrestchang** [comment]
git 理论上是没有大小限制的，但是 github 的 repository 有最大 100G 的限制，并规定每个文件不能大于 100 MB。

> We recommend repositories be kept under 1GB each. Repositories have a hard limit of 100GB. If you reach 75GB you'll receive a warning from Git in your terminal when you push. This limit is easy to stay within if large files are kept out of the repository. If your repository exceeds 1GB, you might receive a polite email from GitHub Support requesting that you reduce the size of the repository to bring it back down.

> In addition, we place a strict limit of files exceeding 100 MB in size. For more information, see "Working with large files."

另外，针对大文件的操作推荐使用 [Git Large File Storage](https://git-lfs.github.com/)

参考：
- [What is my disk quota? - GitHub Help](https://help.github.com/en/articles/what-is-my-disk-quota)
