### ISSUE TITLE
Our long-standing concerns(From EECS, Academy Department)

### ISSUE THREAD

**Issue by AaronAnima** [lib-pku/libpku#9]
1.I want to know whether you are an organization or an individual of PKU. In fact we need to discuss privately about some serious problems, so we're trying to contact with you.
2.We wonder whether you have got the permission from owners/teachers. Cuz in most cases, teachers are not willing to release the classware or test-papers.
3.Have you ever considered that someone would use this materials for commercial purposes?

**Comment by librarian-pku** [comment]
1. We are students in PKU, thank you for your interest, you can send email to  libpku@protonmail.com
2. (3.)We collected the materials from the Internet, but your concern might make sense, we can discuss further in emails.

BTW, WE wonder whether YOU have got the permission from owners/teachers in EECS-PKU-XSB/Shared-learning-materials.
